// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYE9jgeERmPaNUs9wYy2DbBuXkIo8u8es',
    appId: '1:719442265707:web:069597043896ba5c3f132e',
    messagingSenderId: '719442265707',
    projectId: 'balance-beats',
    authDomain: 'balance-beats.firebaseapp.com',
    storageBucket: 'balance-beats.appspot.com',
    measurementId: 'G-6R6CHNTJD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTPGKpWZHA7IUaRc9YD3GkurilJ-R-yU',
    appId: '1:719442265707:android:c1b9538e5a24da353f132e',
    messagingSenderId: '719442265707',
    projectId: 'balance-beats',
    storageBucket: 'balance-beats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneyybSGL45sa7BRO_nBEpC7E32vnGqXk',
    appId: '1:719442265707:ios:464929831b585e0a3f132e',
    messagingSenderId: '719442265707',
    projectId: 'balance-beats',
    storageBucket: 'balance-beats.appspot.com',
    iosBundleId: 'com.example.balencebeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneyybSGL45sa7BRO_nBEpC7E32vnGqXk',
    appId: '1:719442265707:ios:63649910d2e9a95c3f132e',
    messagingSenderId: '719442265707',
    projectId: 'balance-beats',
    storageBucket: 'balance-beats.appspot.com',
    iosBundleId: 'com.example.balencebeats.RunnerTests',
  );
}
